// Enhanced mock data for filtering
export const mockStudents = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    rollNumber: "CS2021001",
    year: "3rd",
    department: "Computer Science",
    section: "A",
    email: "john.doe@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    rollNumber: "CS2021002",
    year: "3rd",
    department: "Computer Science",
    section: "A",
    email: "jane.smith@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 3,
    firstName: "Mike",
    lastName: "Johnson",
    rollNumber: "CS2022001",
    year: "2nd",
    department: "Computer Science",
    section: "B",
    email: "mike.johnson@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Wilson",
    rollNumber: "IT2021001",
    year: "3rd",
    department: "Information Technology",
    section: "A",
    email: "sarah.wilson@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    rollNumber: "CS2023001",
    year: "1st",
    department: "Computer Science",
    section: "A",
    email: "david.brown@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 6,
    firstName: "Emily",
    lastName: "Davis",
    rollNumber: "IT2022001",
    year: "2nd",
    department: "Information Technology",
    section: "B",
    email: "emily.davis@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 7,
    firstName: "Alex",
    lastName: "Miller",
    rollNumber: "CS2020001",
    year: "4th",
    department: "Computer Science",
    section: "A",
    email: "alex.miller@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 8,
    firstName: "Lisa",
    lastName: "Garcia",
    rollNumber: "MATH2021001",
    year: "3rd",
    department: "Mathematics",
    section: "A",
    email: "lisa.garcia@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 9,
    firstName: "Tom",
    lastName: "Anderson",
    rollNumber: "IT2023001",
    year: "1st",
    department: "Information Technology",
    section: "C",
    email: "tom.anderson@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 10,
    firstName: "Anna",
    lastName: "Taylor",
    rollNumber: "MATH2022001",
    year: "2nd",
    department: "Mathematics",
    section: "B",
    email: "anna.taylor@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const mockFaculty = [
  {
    id: 101,
    name: "Dr. Robert Brown",
    department: "Computer Science",
    designation: "Professor",
    email: "robert.brown@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 102,
    name: "Prof. Lisa Davis",
    department: "Information Technology",
    designation: "Associate Professor",
    email: "lisa.davis@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 103,
    name: "Dr. Mark Wilson",
    department: "Computer Science",
    designation: "Assistant Professor",
    email: "mark.wilson@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 104,
    name: "Prof. Emily Johnson",
    department: "Mathematics",
    designation: "Professor",
    email: "emily.johnson@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 105,
    name: "Dr. James Lee",
    department: "Information Technology",
    designation: "Assistant Professor",
    email: "james.lee@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 106,
    name: "Prof. Maria Rodriguez",
    department: "Mathematics",
    designation: "Associate Professor",
    email: "maria.rodriguez@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 107,
    name: "Dr. Kevin White",
    department: "Computer Science",
    designation: "Professor",
    email: "kevin.white@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 108,
    name: "Prof. Rachel Green",
    department: "Information Technology",
    designation: "Professor",
    email: "rachel.green@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

// Filter options
export const filterOptions = {
  years: ["1st", "2nd", "3rd", "4th"],
  departments: ["Computer Science", "Information Technology", "Mathematics", "Physics", "Chemistry"],
  sections: ["A", "B", "C"],
  designations: ["Professor", "Associate Professor", "Assistant Professor", "Lecturer"],
}
